context:
  name: azure-mgmt-synapse
  version: 2.1.0b7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-synapse-${{ version }}.zip
    sha256: f5d88154f594a1f11ad4b272b5a0ce53614a07b9c50e96b25a09a7ab7971e9d6

build:
<<<<<<< HEAD
  number: 1
=======
  number: 2
>>>>>>> origin/main
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python
    - msrest >=0.7.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing-extensions >=4.3.0

tests:
  - python:
      imports:
        - azure.mgmt.synapse
        - azure.mgmt.synapse.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Synapse Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
