context:
  name: azure-mgmt-synapse
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-synapse-${{ version }}.zip
    sha256: bec6bdfaeb55b4fdd159f2055e8875bf50a720bb0fce80a816e92a2359b898c8
  - url: https://raw.githubusercontent.com/Azure/azure-sdk-for-python/50471e7f07b430ab0bbc1984cd2fc102d908de41/sdk/synapse/azure-mgmt-synapse/LICENSE
    sha256: 7c77a44a8acd9b41fdc209864a8016b3d430b5d0e09309818d5b7444336df744

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - msrest >=0.6.21
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.2.0,<2.0.0

tests:
  - python:
      imports:
        - azure.mgmt.synapse
        - azure.mgmt.synapse.aio
      pip_check: true

about:
  summary: Microsoft Azure Synapse Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
